version: "3.8"
services:
  mi-mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    restart: always
    environment:
      # Provide your credentials here
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mi-mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mi-mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mi-mongo

  mi-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file: ./api/.env.docker
    restart: always
    ports:
      - 4004:4004
    depends_on:
      - mi-mongo
    volumes:
      - cdn:/var/www/cdn/movinin

  mi-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - mi-api
    ports:
      - 3003:3003

  mi-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - mi-api
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - cdn:/var/www/cdn/movinin

volumes:
  cdn:
  mongodb_data:
  mongodb_config:
