services:
  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  mi-dev-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    env_file: ./api/.env.docker
    restart: always
    ports:
      - 4004:4004
    depends_on:
      - mongo
    volumes:
      - cdn:/var/www/cdn/movinin
      - ./api:/movinin/api
      - /movinin/api/node_modules
      - api_logs:/movinin/api/logs

  mi-dev-admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile.dev
    env_file: ./admin/.env.docker
    restart: always
    depends_on:
      - mi-dev-api
    ports:
      - 3003:3003
    volumes:
      - ./admin:/movinin/admin
      - /movinin/admin/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  mi-dev-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    env_file: ./frontend/.env.docker
    restart: always
    depends_on:
      - mi-dev-api
    ports:
      - 8081:8081
      - 8444:443
    volumes:
      - ./frontend:/movinin/frontend
      - /movinin/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  cdn:
  mongodb_data:
  mongodb_config:
  api_logs:
