version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file: ./backend/.env.docker
    restart: always
    ports:
      - 4004:4004
    depends_on:
      - mongo
    volumes:
      - cdn:/var/www/cdn/movinin

  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    restart: always
    environment:
      # Provide your credentials here
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    ports:
      - 27017:27017

  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    depends_on:
      - backend
    ports:
      - 3003:3003

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - cdn:/var/www/cdn/movinin

volumes:
  cdn:
