name: Update Mobile App URL

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-latest-release-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Determine TAG_NAME
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
          else
            echo "Fetching latest release tag from GitHub API..."
            TAG_NAME=$(curl -s https://api.github.com/repos/aelassas/movinin/releases/latest | jq -r '.tag_name')
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "VERSION=${TAG_NAME#v}" >> $GITHUB_ENV

      - name: Update .github/latest-release.json
        run: |
          echo "{\"latestApkUrl\": \"https://github.com/aelassas/movinin/releases/download/${TAG_NAME}/movinin-${VERSION}.apk\"}" > .github/latest-release.json

      - name: Commit and push latest-release.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Switch to the default branch
          git fetch origin
          DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          git checkout $DEFAULT_BRANCH
          git pull origin $DEFAULT_BRANCH

          git add .github/latest-release.json
          git diff --cached --quiet || git commit -m "chore: update latest-release.json for ${TAG_NAME}"
          
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin $DEFAULT_BRANCH
